apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespacewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespacewatch
  template:
    metadata:
      labels:
        name: namespacewatch
    spec:
      serviceAccountName: namespacewatch
      containers:
        - name: namespacewatch
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - namespacewatch
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespacewatch"
