kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespacewatch
subjects:
- kind: ServiceAccount
  name: namespacewatch
roleRef:
  kind: Role
  name: namespacewatch
  apiGroup: rbac.authorization.k8s.io
